type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start 0:
      type: "start"
      transitions:
        unconditional:
        - "Query Result To Scalar 0"
      parameters:
        componentName: "Start 0"
    If 0:
      type: "if"
      transitions:
        "true":
        - "Change password"
      parameters:
        componentName: "If 0"
        mode: "Simple"
        condition:
        - - "v_changePwd_0"
          - "Is"
          - "Equal to"
          - "1"
        combineConditions: "And"
    Change password:
      type: "sql-script"
      parameters:
        componentName: "Change password"
        sqlScript: |-
          use role ACCOUNTADMIN;

          alter user if exists ANOUSACKPHILAVANH SET MUST_CHANGE_PASSWORD = TRUE;
          alter user if exists ANTHONYGONZALEZ SET MUST_CHANGE_PASSWORD = TRUE;
          alter user if exists BIBIANAPASSADORE SET MUST_CHANGE_PASSWORD = TRUE;
          alter user if exists HOURIAMERABTENE SET MUST_CHANGE_PASSWORD = TRUE;
          alter user if exists ILANCHEMLA SET MUST_CHANGE_PASSWORD = TRUE;
          alter user if exists JOHNTHEIOS SET MUST_CHANGE_PASSWORD = TRUE;
          alter user if exists LYESBOUKEROUI SET MUST_CHANGE_PASSWORD = TRUE;
          alter user if exists OLIVIERQUIGNON SET MUST_CHANGE_PASSWORD = TRUE;
          alter user if exists PHILIPPECHASSAGNARD SET MUST_CHANGE_PASSWORD = TRUE;
          alter user if exists SANYATMOHAMED SET MUST_CHANGE_PASSWORD = TRUE;
          alter user if exists STEPHANIEGAUTHIER SET MUST_CHANGE_PASSWORD = TRUE;
          alter user if exists ALEXBOSS SET MUST_CHANGE_PASSWORD = TRUE;

          use role ETL_PROD;
    Query Result To Scalar 0:
      type: "query-to-scalar"
      transitions:
        success:
        - "If 0"
      parameters:
        componentName: "Query Result To Scalar 0"
        mode: "Advanced"
        query: |
          select iff(dayofyear(current_date()) in (90, 180, 270, 360), 1, 0) as changepwd
        scalarVariableMapping:
        - - "v_changePwd_0"
          - "CHANGEPWD"
  variables:
    v_changePwd_0:
      metadata:
        type: "TEXT"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: ""
design:
  components:
    Start 0:
      position:
        x: -400
        "y": 32
      tempMetlId: 73492
    If 0:
      position:
        x: -96
        "y": 32
      tempMetlId: 73494
    Change password:
      position:
        x: 64
        "y": 32
      tempMetlId: 73495
    Query Result To Scalar 0:
      position:
        x: -240
        "y": 32
      tempMetlId: 73497
