type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start 0:
      type: "start"
      transitions:
        unconditional:
        - "Create Table 0"
      parameters:
        componentName: "Start 0"
    "00_02_T_DIM_DATE":
      type: "run-transformation"
      parameters:
        componentName: "00_02_T_DIM_DATE"
        transformationJob: "00 _F_GLOBAL/00_02_F_DIM_DATE/00_02_T_DIM_DATE"
        setScalarVariables:
        setGridVariables:
    Google Sheets Query 0:
      type: "unknown-orchestration"
      transitions:
        success:
        - "00_02_T_DIM_DATE"
      parameters:
        componentName: "Google Sheets Query 0"
    Create Table 0:
      type: "create-table"
      transitions:
        success:
        - "Google Sheets Query 0"
      parameters:
        componentName: "Create Table 0"
        createReplace: "Create if not exists"
        database: "[Environment Default]"
        schema: "ODS"
        newTableName: "DIM_DATE"
        columns:
        - - "DATE"
          - "TIMESTAMP"
          - "9"
          - ""
          - ""
          - "Yes"
          - "Yes"
        - - "YEAR"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "No"
          - "No"
        - - "SEMESTER"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "No"
          - "No"
        - - "QUARTER"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "No"
          - "No"
        - - "MONTH"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "No"
          - "No"
        - - "WEEK"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "No"
          - "No"
        - - "DAY"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "No"
          - "No"
        - - "WEEK_DAY_NUMBER"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "No"
          - "No"
        - - "WEEK_DAY_NAME"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "No"
          - "No"
        - - "WEEK_DAY_NAME_NUMBER"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "No"
          - "No"
        - - "MONTH_LAST_DAY_DATE"
          - "TIMESTAMP"
          - ""
          - ""
          - ""
          - "No"
          - "No"
        - - "WEEK_FIRST_DAY_DATE"
          - "TIMESTAMP"
          - ""
          - ""
          - ""
          - "No"
          - "No"
        - - "YEAR_SEMESTER"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "No"
          - "No"
        - - "YEAR_QUARTER"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "No"
          - "No"
        - - "YEAR_MONTH"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "No"
          - "No"
        - - "YEAR_WEEK"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "No"
          - "No"
        - - "YOY_DATE"
          - "TIMESTAMP"
          - ""
          - ""
          - ""
          - "No"
          - "No"
        - - "YOY_SEMESTER"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "No"
          - "No"
        - - "YOY_QUARTER"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "No"
          - "No"
        - - "YOY_MONTH"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "No"
          - "No"
        - - "YOY_WEEK"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "No"
          - "No"
        - - "WOW_DATE"
          - "TIMESTAMP"
          - ""
          - ""
          - ""
          - "No"
          - "No"
        - - "WOW_WEEK"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "No"
          - "No"
        primaryKeys:
        - "DATE"
        clusteringKeys:
        dataRetentionTimeInDays: ""
        comment: ""
design:
  components:
    Start 0:
      position:
        x: -266
        "y": 4
      tempMetlId: 73634
    "00_02_T_DIM_DATE":
      position:
        x: 260
        "y": 2
      tempMetlId: 73636
    Google Sheets Query 0:
      position:
        x: 42
        "y": -3
      tempMetlId: 73637
    Create Table 0:
      position:
        x: -113
        "y": 6
      tempMetlId: 73639
